# Generated by Django 3.1.6 on 2021-02-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('cc', models.CharField(max_length=2)),
                ('has_toplist', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'db_table': 'liga',
                'managed': True,
            },
        ),
    ]
