# Generated by Django 3.1.6 on 2021-02-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0002_liga_has_leaguetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='cc',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
