# Generated by Django 3.1.6 on 2021-02-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ligas', '0001_initial'),
        ('times', '0002_time_cc'),
    ]

    operations = [
        migrations.CreateModel(
            name='jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_partida', models.BigIntegerField(unique=True)),
                ('time_casa', models.CharField(max_length=80)),
                ('time_visitante', models.CharField(max_length=80)),
                ('liga', models.CharField(max_length=80)),
                ('cc', models.CharField(max_length=2)),
                ('ss', models.CharField(max_length=4)),
                ('data_partida', models.DateTimeField()),
                ('qtd_gol_casa', models.PositiveIntegerField(default=0)),
                ('qtd_gol_visitante', models.PositiveIntegerField(default=0)),
                ('realizada', models.BooleanField()),
                ('id_liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligas.liga')),
                ('id_time_casa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casa', to='times.time')),
                ('id_time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitante', to='times.time')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'db_table': 'jogo',
                'managed': True,
            },
        ),
    ]
