# Generated by Django 3.1.5 on 2021-01-31 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_min_aposta', models.DecimalField(decimal_places=2, max_digits=9)),
                ('val_max_aposta', models.DecimalField(decimal_places=2, max_digits=9)),
                ('val_max_aposta_aovivo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('premio_maximo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('contacao_mini_bilhete', models.DecimalField(decimal_places=2, max_digits=9)),
                ('npg_comissão_apostas_cota_menor', models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Não pagar comissão em apostas com cota menor que:')),
                ('cotacaomaxima_Bilhete', models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Cotação Máxima no Bilhete')),
                ('nao_exibir_cotacoes_menores', models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Não Exibir Cotações Menores Que:')),
                ('qtd_mini_jogos_bilhetes', models.PositiveIntegerField(default=1, verbose_name='Quantidade mínima de jogos por bilhete:')),
                ('qtd_max_jogos_bilhetes', models.PositiveIntegerField(default=1, verbose_name='Quantidade máxima de jogos por bilhete:')),
                ('texto_rodape', models.CharField(default='Valor maximo pago no premio é de R$50.000,00', max_length=80)),
                ('email_alerta', models.EmailField(max_length=150)),
                ('cambista_cancelar_bilhete', models.BooleanField(default=True)),
                ('exibir_bilhetes_gerentes_camistas', models.BooleanField(default=True)),
                ('tempo_cancelamento', models.PositiveIntegerField(default=15)),
                ('apostas_ativas', models.BooleanField(default=True)),
                ('alertar_apostas_acima', models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Alertar apostas acima de:')),
                ('alertar_apostas_simples_contacao_acima', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Alertar cupons de apostas simples com cotações acima de:')),
                ('alertar_apostas_multiplas_contacao_acima', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Alertar cupons de apostas múltiplas com cotação acima de:')),
                ('limite_aposta_simples_todos_cambistas', models.PositiveIntegerField(verbose_name='Limite de apostas simples de todos os cambistas após prestar contas:')),
                ('limite_aposta_geral_todos_cambistas', models.PositiveIntegerField(verbose_name='Limite de apostas geral de todos os cambistas após prestar contas:')),
                ('val_max_contacoes', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Máximo para Cotações')),
                ('comissao_padrao', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Comissão padrão (%):')),
                ('comissao_padrao_ao_vivo', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Comissão padrão ao vivo (%):')),
                ('id_banca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancas.banca')),
            ],
            options={
                'verbose_name': 'Configuracao',
                'verbose_name_plural': 'Configurações',
                'db_table': 'configuracao',
                'managed': True,
            },
        ),
    ]
