# Generated by Django 3.1.6 on 2021-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambistas', '0002_auto_20210131_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambista',
            name='celular',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
