# Generated by Django 3.1.5 on 2021-01-31 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('numero_pix', models.CharField(max_length=150, unique=True)),
                ('data_cad', models.DateTimeField(auto_now=True)),
                ('id_usr', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bonus_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('id_apostador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'db_table': 'conta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorioConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentacao', models.CharField(choices=[('Compra creditos', 'Comprar creditos'), ('Retirar creditos', 'Retirar creditos'), ('Bonuns', 'Bonuns')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('movi_data', models.DateTimeField(auto_now=True)),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.conta')),
            ],
            options={
                'verbose_name': 'historico',
                'verbose_name_plural': 'historicos',
                'db_table': 'historicoconta',
                'managed': True,
            },
        ),
    ]
