# Generated by Django 3.1.6 on 2021-02-05 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_adm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administradores.administrador')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
