# Generated by Django 3.1.6 on 2021-02-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancas', '0003_remove_banca_data_cad'),
        ('apostas', '0011_remove_aposta_id_banca'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_conta', models.CharField(max_length=40)),
                ('id_banca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancas.banca')),
            ],
        ),
        migrations.CreateModel(
            name='ConasReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movi', models.DateTimeField(auto_created=True)),
                ('descricao', models.CharField(max_length=40)),
                ('codigo_doc', models.CharField(max_length=40)),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valor_tota', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status_rebe', models.CharField(choices=[('Finalizado', 'Finalizado'), ('Em aberto', 'Em aberto'), ('Vencido', 'Vencido')], max_length=30)),
                ('id_apostas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apostas.aposta')),
                ('id_banca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancas.banca')),
                ('id_plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiros.planocontas')),
            ],
        ),
        migrations.CreateModel(
            name='ConasPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_mov', models.DateTimeField(auto_created=True)),
                ('descricao', models.CharField(max_length=40)),
                ('codigo_doc', models.CharField(max_length=40)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status_pg', models.CharField(choices=[('Finalizado', 'Finalizado'), ('Em aberto', 'Em aberto'), ('Vencido', 'Vencido')], max_length=30)),
                ('id_banca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancas.banca')),
                ('id_plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiros.planocontas')),
            ],
        ),
    ]
