# Generated by Django 3.1.6 on 2021-02-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conaspagar',
            name='comprovate',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='conasreceber',
            name='comprovate',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
