# Generated by Django 3.1.7 on 2021-03-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancas', '0003_remove_banca_data_cad'),
        ('apostas', '0012_detalheaposta'),
        ('financeiros', '0002_auto_20210205_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConasPagar',
            new_name='ContasPagar',
        ),
        migrations.RenameModel(
            old_name='ConasReceber',
            new_name='ContasReceber',
        ),
    ]
