# Generated by Django 3.1.6 on 2021-02-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_time_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='id_img',
            field=models.IntegerField(default=0),
        ),
    ]
