# Generated by Django 3.1.6 on 2021-02-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_auto_20210213_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='id_img',
            new_name='image_id',
        ),
    ]
