# Generated by Django 3.1.5 on 2021-01-31 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancas', '0002_auto_20210131_1942'),
        ('apostas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='id_banca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bancas.banca'),
            preserve_default=False,
        ),
    ]
