# Generated by Django 3.1.5 on 2021-01-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0006_aposta_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='tipo',
            field=models.CharField(choices=[('Aposta Múltipla', 'Aposta Múltipla'), ('Aposta Simples', 'Aposta Simples')], default='Aposta Múltipla', max_length=60),
            preserve_default=False,
        ),
    ]
