# Generated by Django 3.1.5 on 2021-01-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0007_aposta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='data_aposta',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
