# Generated by Django 3.1.6 on 2021-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0009_auto_20210131_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='tipo',
            field=models.CharField(choices=[('Aposta Múltipla', 'Aposta Múltipla'), ('Aposta Simples', 'Aposta Simples'), ('Aposta online', 'Aposta online')], max_length=60),
        ),
    ]
