# Generated by Django 3.1.6 on 2021-02-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0010_auto_20210204_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='id_banca',
        ),
    ]
