# Generated by Django 3.1.7 on 2021-03-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
        ('apostas', '0011_remove_aposta_id_banca'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheAposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aposta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='det_aposta', to='apostas.aposta')),
                ('id_jogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jogos.jogo')),
            ],
        ),
    ]
